"""
VC (Vulnerable Customer) keyword list for immediate transfer to
AD Vulnerable Customer Keyword Triggered (+1 (555) 000-1234).

Known VC (ANI in DB) + keyword → still routes to main VC line (+1 (555) 000-1234).
"""

from _gen import *  # <AUTO GENERATED>

# list of keywords
VC_KEYWORDS_PHRASES = [
    "you have a call from a deaf or a speech impaired person, please wait for a relay assistant",
    "assisted living",
    "bed bound",
    "bed ridden",
    "cant cope",
    "care home",
    "cost of living",
    "court of protection",
    "domestic abuse",
    "downs syndrome",
    "end of life",
    "financial difficulty",
    "guide dog",
    "have difficulty",
    "hearing aid",
    "heart attack",
    "i can't do that",
    "i'm a disabled",
    "i'm disabled",
    "individual voluntary arrangement",
    "intensive care",
    "life support",
    "long cane",
    "lost job",
    "medical treatment",
    "memory loss",
    "mobility scooter",
    "multiple sclerosis",
    "next of kin",
    "non verbal",
    "palliative care",
    "panic attack",
    "passed away",
    "power of attorney",
    "sign language",
    "single father",
    "single mother",
    "single parent",
    "special needs",
    "stressed out",
    "temporary accommodation",
    "terminal illness",
    "third party mandate",
    "threat to life",
    "universal credit",
    "victim of abuse",
    "walking aid",
    "walking stick",
    "white cane",
    "disabled brother",
    "disabled child",
    "disabled daughter",
    "disabled person",
    "disabled sister",
    "disabled son",
    "relay uk",
    "synthetic voice",
]

# Single words (client list as provided; normalized to lowercase for matching)
VC_KEYWORDS_SINGLE = [
    "abused",
    "abuser",
    "abusing",
    "abusive",
    "accessibility",
    "acute",
    "addict",
    "addicted",
    "addiction",
    "addictive",
    "adhd",
    "agoraphobia",
    "aids",
    "alcohol",
    "alzheimer",
    "ambulance",
    "amnesia",
    "amputat",
    "anxiety",
    "anxious",
    "aphasia",
    "arrears",
    "arthrit",
    "arthritis",
    "aspergers",
    "asthma",
    "asylum",
    "atrophy",
    "atypical",
    "autism",
    "autistic",
    "bankrupt",
    "bereave",
    "bereaved",
    "bereavement",
    "bereaving",
    "binary",
    "bipolar",
    "blind",
    "blood",
    "braille",
    "breakdown",
    "bsl",
    "cancer",
    "cardiovascular",
    "carer",
    "cerebral",
    "cerebrovascular",
    "cfs",
    "chronic",
    "coerced",
    "coercion",
    "coercive",
    "cognitive",
    "coma",
    "concentrate",
    "concentration",
    "congential",
    "covid",
    "crisis",
    "crutches",
    "dead",
    "deaf",
    "death",
    "deaths",
    "debt",
    "degeneratation",
    "degenerative",
    "degnerative",
    "dementia",
    "depressed",
    "depression",
    "deputyship",
    "dexterity",
    "diabetes",
    "die",
    "died",
    "disability",
    "disabled",
    "disease",
    "disorder",
    "divorce",
    "doctor",
    "donor",
    "drugs",
    "dv",
    "dwp",
    "dying",
    "dyscalculia",
    "dyslexia",
    "dyspraxia",
    "elderly",
    "emergency",
    "emotional",
    "english",
    "enslaved",
    "epilepsy",
    "esa",
    "evicted",
    "exhaustion",
    "faint",
    "fatigue",
    "fibromyalgia",
    "funeral",
    "gambled",
    "gambler",
    "gambling",
    "gender",
    "glaucoma",
    "guardianship",
    "hardship",
    "harm",
    "harmed",
    "harmful",
    "harming",
    "health",
    "heating",
    "hiv",
    "homeless",
    "hospice",
    "hospital",
    "hypertension",
    "ill",
    "illiterate",
    "illness",
    "immigrant",
    "impairment",
    "incapacity",
    "injured",
    "insolvency",
    "insomnia",
    "interpret",
    "iva",
    "kill",
    "killed",
    "killer",
    "killing",
    "leukemia",
    "loneliness",
    "lonely",
    "lymphomoa",
    "malignan",
    "manipulate",
    "manipulated",
    "manipulation",
    "md",
    "medicate",
    "medicating",
    "medication",
    "mentally",
    "mh",
    "mnd",
    "mobility",
    "mourning",
    "ms",
    "murder",
    "murderous",
    "murders",
    "narcolepsy",
    "neurological",
    "neurone",
    "nok",
    "ocd",
    "overdose",
    "overdosed",
    "overdosing",
    "overwhelmed",
    "paralyse",
    "paranoia",
    "paranoid",
    "parkinson",
    "parkinsons",
    "pensioner",
    "phobia",
    "pip",
    "pregnancy",
    "pregnant",
    "prison",
    "psychiatric",
    "psychological",
    "psyschosis",
    "psyschotic",
    "ptsd",
    "refugee",
    "rehab",
    "repossession",
    "schizophrenia",
    "schizophrenic",
    "sectioned",
    "seizure",
    "self-harm",
    "senile",
    "shelter",
    "shielding",
    "shock",
    "shocked",
    "shocking",
    "shout at",
    "sickle",
    "sighted",
    "slave",
    "slavery",
    "sleeplessness",
    "stamina",
    "stammer",
    "starv",
    "stomach",
    "stress",
    "stroke",
    "struggle",
    "stutter",
    "suffering",
    "suicidal",
    "suicide",
    "surgery",
    "survive",
    "survivor",
    "syndrome",
    "terminal",
    "threat",
    "threatened",
    "threatening",
    "tinnitus",
    "tourettes",
    "transgender",
    "trauma",
    "traumatic",
    "tremor",
    "tumour",
    "unwell",
    "victim",
    "violen",
    "violence",
    "violent",
    "vulnerable",
    "wheelchair",
]

# Combined: phrases first so e.g. "assisted living" matches before "assisted" or "living"
VC_KEYWORDS = VC_KEYWORDS_PHRASES + VC_KEYWORDS_SINGLE


@func_description("utils function for VC handoff key words")
def vc_keywords(conv: Conversation):
    conv.state.vc_keywords = get_vc_keywords_for_prompt()


def get_vc_keywords_for_prompt() -> str:
    """String of VC keywords for injection into agent rules (e.g. $vc_keywords)."""
    return ", ".join(VC_KEYWORDS)
