handoffs:
- name: Account_Closure
  description: ''
  is_default: false
  sip_config:
    method: refer
    phone_number: <sip:+1234567890@54.154.39.202>
- name: Cards
  description: ''
  is_default: false
  sip_config:
    method: refer
    phone_number: <sip:+1234567890@54.154.39.202>
- name: Digital_Skill
  description: ''
  is_default: false
  sip_config:
    method: refer
    phone_number: <sip:+1234567890@54.154.39.202>
- name: EoD_Skill
  description: ''
  is_default: false
  sip_config:
    method: refer
    phone_number: <sip:+1234567890@54.154.39.202>
- name: Payments_Skill
  description: ''
  is_default: false
  sip_config:
    method: refer
    phone_number: <sip:+1234567890@54.154.39.202>
- name: Vulnerable_Customer
  description: ''
  is_default: false
  sip_config:
    method: refer
    phone_number: <sip:+1234567890@54.154.39.202>
- name: Vulnerable_Customer_Skill
  description: ''
  is_default: false
  sip_config:
    method: refer
    phone_number: <sip:+1234567890@54.154.39.202>
- name: Overdrafts
  description: ''
  is_default: false
  sip_config:
    method: refer
    phone_number: <sip:+1234567890@54.154.39.202>
- name: BBLS Skill
  description: ''
  is_default: false
  sip_config:
    method: refer
    phone_number: <sip:+1234567890@54.154.39.202>
- name: Business CSC Skill
  description: ''
  is_default: false
  sip_config:
    method: refer
    phone_number: <sip:+1234567890@54.154.39.202>
- name: Business Cards Skill
  description: ''
  is_default: false
  sip_config:
    method: refer
    phone_number: <sip:+1234567890@54.154.39.202>
- name: Business Payments Skill
  description: ''
  is_default: false
  sip_config:
    method: refer
    phone_number: <sip:+1234567890@54.154.39.202>
- name: ISA Skill
  description: ''
  is_default: false
  sip_config:
    method: refer
    phone_number: <sip:+1234567890@54.154.39.202>
- name: IVR
  description: ''
  is_default: false
  sip_config:
    method: refer
    phone_number: <sip:+1234567890@54.154.39.202>
- name: Mortgages Application In Process
  description: ''
  is_default: false
  sip_config:
    method: refer
    phone_number: <sip:+1234567890@54.154.39.202>
- name: Mortgages Broker
  description: ''
  is_default: false
  sip_config:
    method: refer
    phone_number: <sip:+1234567890@54.154.39.202>
- name: Mortgages Existing General
  description: ''
  is_default: false
  sip_config:
    method: refer
    phone_number: <sip:+1234567890@54.154.39.202>
- name: Mortgages Financial Difficulty
  description: ''
  is_default: false
  sip_config:
    method: refer
    phone_number: <sip:+1234567890@54.154.39.202>
- name: Mortgages New Application
  description: ''
  is_default: false
  sip_config:
    method: refer
    phone_number: <sip:+1234567890@54.154.39.202>
- name: SP1
  description: ''
  is_default: false
  sip_config:
    method: refer
    phone_number: <sip:+1234567890@54.154.39.202>
- name: T1 Lite Skill
  description: ''
  is_default: false
  sip_config:
    method: refer
    phone_number: <sip:+1234567890@54.154.39.202>
- name: T1 Skill
  description: ''
  is_default: true
  sip_config:
    method: refer
    phone_number: <sip:+1234567890@54.154.39.202>
- name: T2 Skill
  description: ''
  is_default: false
  sip_config:
    method: refer
    phone_number: <sip:+1234567890@54.154.39.202>
- name: TMS Disputes
  description: ''
  is_default: false
  sip_config:
    method: refer
    phone_number: <sip:+1234567890@54.154.39.202>
- name: TMS Fraud
  description: ''
  is_default: false
  sip_config:
    method: refer
    phone_number: <sip:+1234567890@54.154.39.202>
- name: W&G TBM
  description: ''
  is_default: false
  sip_config:
    method: refer
    phone_number: <sip:+1234567890@54.154.39.202>
- name: Specialist_1
  description: ''
  is_default: false
  sip_config:
    method: refer
    phone_number: <sip:+1234567890@54.154.39.202>
- name: Tier_2
  description: ''
  is_default: false
  sip_config:
    method: refer
    phone_number: <sip:+1234567890@54.154.39.202>
- name: Business Expert
  description: ''
  is_default: false
  sip_config:
    method: refer
    phone_number: <sip:+1234567890@54.154.39.202>
- name: Vulnerable_Customer_Keyword_Triggered
  description: ''
  is_default: false
  sip_config:
    method: refer
    phone_number: <sip:+1234567890@54.154.39.202>
