greeting:
  welcome_message: "[Ring] Hi, thanks for calling Poly Store! How can I help you today?"
  language_code: en-US
style_prompt:
  prompt: ""
disclaimer_messages:
  message: ""
  enabled: false
  language_code: en-US
